version: 2

sources:
  - name: raw_data
    schema: test_python_schema_raw_data
    tables:
      - name: events
        tags: ["events"]
      - name: users

  - name: dagster
    schema: dagster
    tables:
      - name: bot_labeled_users
